/**
 * Amiga LPF coefficient + magnitude pins (D114).
 *
 * The goldens below were derived OFFLINE with an independently implemented
 * bilinear transform (prewarped analog prototypes substituted through
 * s = 2*fs*(1 - z^-1)/(1 + z^-1); see the derivation notes in
 * amiga-filter-math.ts) -- they are committed literals and were never
 * generated by the module under test. The magnitude pins then run a pure-TS
 * IIR recursion through the stage's *real* coefficient pipeline
 * (`params -> AmigaLpfStage -> getCoefficients()`), so they end-to-end the
 * code that ships, per the jt_letgo load-path rule.
 *
 * Pins that specifically catch a Q/zeta mix-up: |H(3275 Hz)| ~= -5.25 dB with
 * a monotone response. A Butterworth-Q (0.7071) would peak ~+1 dB at fc; a
 * zeta-as-Q implementation lands ~-3 dB there instead.
 */

import { describe, expect, it } from 'vitest';
import {
  deriveAmigaLpfCoefficients,
  type AmigaLpfCoefficients,
} from '../postfx/amiga-filter-math';
import { AmigaLpfStage } from '../postfx/amiga-lpf-stage';

// ---------------------------------------------------------------------------
// Minimal factory stub: the stage needs nodes to exist; the pins only read
// coefficients out of it.
// ---------------------------------------------------------------------------
function recordingFactory() {
  const iirNodes: Array<{ ff: number[]; fb: number[] }> = [];
  return {
    iirNodes,
    factory: {
      createGain: () =>
        ({
          gain: { value: 0 },
          connect: (): void => undefined,
          disconnect: (): void => undefined,
        }) as unknown as GainNode,
      createIIRFilter: (ff: number[], fb: number[]) => {
        const node = {
          ff,
          fb,
          connect: (): void => undefined,
          disconnect: (): void => undefined,
        };
        iirNodes.push(node);
        return node as unknown as IIRFilterNode;
      },
    },
  };
}

function stageAt(fs: number): AmigaLpfStage {
  return new AmigaLpfStage(
    { sampleRate: fs } as unknown as BaseAudioContext,
    undefined,
    recordingFactory().factory,
  );
}

/**
 * Golden coefficients at fs = 44100 / 48000 / 96000, rounded to 5 decimal
 * places. Derived independently (scipy.signal.bilinear on prewarped analog
 * prototypes; derivation session 2026-09-04).
 */
const GOLDEN_COEFFICIENTS = {
  44100: {
    rc: { b0: 0.26685, b1: 0.26685, a1: -0.46631 },
    led: { b0: 0.03975, b1: 0.07949, b2: 0.03975, a1: -1.32823, a2: 0.48721 },
  },
  48000: {
    rc: { b0: 0.24935, b1: 0.24935, a1: -0.50131 },
    led: { b0: 0.03431, b1: 0.06863, b2: 0.03431, a1: -1.3795, a2: 0.51676 },
  },
  96000: {
    rc: { b0: 0.13922, b1: 0.13922, a1: -0.72155 },
    led: { b0: 0.00984, b1: 0.01968, b2: 0.00984, a1: -1.68029, a2: 0.71964 },
  },
} as const;

/**
 * Golden magnitudes in dB through the cascade (RC first, then LED for the
 * "on" state), independently computed from the same offline derivation.
 */
const GOLDEN_MAGNITUDES_DB = {
  44100: {
    off: { '100': -0.0017, '1000': -0.1638, '3275': -1.542, '4900': -3.0103, '5000': -3.1068, '10000': -8.2156 },
    on: { '100': -0.003, '1000': -0.3328, '3275': -5.2523, '4900': -11.6579, '5000': -12.0648, '10000': -30.7712 },
  },
  96000: {
    off: { '100': -0.0018, '1000': -0.1744, '3275': -1.591, '4900': -3.0103, '5000': -3.1005, '10000': -7.3278 },
    on: { '100': -0.0032, '1000': -0.3487, '3275': -5.3013, '4900': -11.3979, '5000': -11.7749, '10000': -27.4808 },
  },
} as const;

describe('golden coefficients (independently derived, 5 dp)', () => {
  for (const fs of [44100, 48000, 96000] as const) {
    it(`reproduce the goldens at fs = ${fs}`, () => {
      const golden = GOLDEN_COEFFICIENTS[fs];
      const c = deriveAmigaLpfCoefficients(fs, {
        staticCutoffHz: 4900,
        ledCutoffHz: 3275,
        ledResDb: -0.7,
      });
      expect(round5(c.rc.b0)).toBe(golden.rc.b0);
      expect(round5(c.rc.b1)).toBe(golden.rc.b1);
      expect(round5(c.rc.a1)).toBe(golden.rc.a1);
      expect(round5(c.led.b0)).toBe(golden.led.b0);
      expect(round5(c.led.b1)).toBe(golden.led.b1);
      expect(round5(c.led.b2)).toBe(golden.led.b2);
      expect(round5(c.led.a1)).toBe(golden.led.a1);
      expect(round5(c.led.a2)).toBe(golden.led.a2);
    });
  }

  it('the coefficients reach the stage nodes through the real pipeline', () => {
    const { iirNodes, factory } = recordingFactory();
    const stage = new AmigaLpfStage(
      { sampleRate: 44100 } as unknown as BaseAudioContext,
      undefined,
      factory,
    );
    // Stage builds rcFilter first, ledFilter second.
    expect(iirNodes[0]!.ff).toEqual([0.2668461709225007, 0.2668461709225007]);
    expect(iirNodes[0]!.fb).toEqual([1, -0.46630765815499864]);
    expect(iirNodes[1]!.ff).toEqual([
      0.03974611973827761, 0.07949223947655522, 0.03974611973827761,
    ]);
    expect(iirNodes[1]!.fb).toEqual([1, -1.3282299043003027, 0.4872143832534132]);
    stage.dispose();
  });
});

describe('magnitude pins through the real coefficient pipeline', () => {
  for (const fs of [44100, 96000] as const) {
    const c: AmigaLpfCoefficients = stageAt(fs).getCoefficients();

    it(`pins the LED-off cascade at fs = ${fs} (RC only, -3 dB at 4900 Hz)`, () => {
      const rc = { b: [c.rc.b0, c.rc.b1], a: [1, c.rc.a1] };
      const magnitudes = GOLDEN_MAGNITUDES_DB[fs].off;
      for (const [freq, golden] of Object.entries(magnitudes)) {
        expect(db(magnitude([rc], Number(freq), fs))).toBeCloseTo(golden, 1);
      }
      // The RC stage's realized -3 dB point is 4900 Hz at every rate (the
      // documented prewarp deviation from libopenmpt's non-prewarped RC).
      expect(db(magnitude([rc], 4900, fs))).toBeCloseTo(-3.0103, 1);
    });

    it(`pins the LED-on cascade at fs = ${fs} (monotone, -5.25 dB at fc)`, () => {
      const rc = { b: [c.rc.b0, c.rc.b1], a: [1, c.rc.a1] };
      const led = { b: [c.led.b0, c.led.b1, c.led.b2], a: [1, c.led.a1, c.led.a2] };
      const magnitudes = GOLDEN_MAGNITUDES_DB[fs].on;
      for (const [freq, golden] of Object.entries(magnitudes)) {
        expect(db(magnitude([rc, led], Number(freq), fs))).toBeCloseTo(golden, 1);
      }
      // |H(3275)| = 1/sqrt(1 + 2*res^2) ~= -5.25 dB: a Butterworth-Q (peaks
      // at fc) or a zeta-as-Q implementation fails this pin.
      const atFc = db(magnitude([rc, led], 3275, fs));
      expect(atFc).toBeLessThan(-5.0);
      expect(atFc).toBeGreaterThan(-5.6);
      // Monotone magnitude -- a1 > sqrt(2) means more damping, no peak.
      const sweep = [100, 500, 1000, 1500, 2000, 2500, 3275, 4000, 5000, 6000, 8000, 10000];
      let previous = Infinity;
      for (const f of sweep) {
        const m = db(magnitude([rc, led], f, fs));
        expect(m).toBeLessThanOrEqual(previous + 1e-9);
        previous = m;
      }
    });
  }

  it('DC gain is 1.0 (+-0.01 dB) in both states', () => {
    for (const fs of [44100, 48000, 96000] as const) {
      const c = deriveAmigaLpfCoefficients(fs, {
        staticCutoffHz: 4900,
        ledCutoffHz: 3275,
        ledResDb: -0.7,
      });
      const rc = { b: [c.rc.b0, c.rc.b1], a: [1, c.rc.a1] };
      const led = { b: [c.led.b0, c.led.b1, c.led.b2], a: [1, c.led.a1, c.led.a2] };
      expect(db(dcGain([rc]))).toBeCloseTo(0, 2);
      expect(db(dcGain([rc, led]))).toBeCloseTo(0, 2);
    }
  });

  it('rolls off 6 dB/octave beyond cutoff (RC stage)', () => {
    const c = deriveAmigaLpfCoefficients(44100, {
      staticCutoffHz: 4900,
      ledCutoffHz: 3275,
      ledResDb: -0.7,
    });
    const rc = { b: [c.rc.b0, c.rc.b1], a: [1, c.rc.a1] };
    // Well beyond fc the one-pole hits its asymptotic 6 dB/octave
    // (6k -> 12k measures ~6.3 dB in the presence of bilinear warping).
    const at6k = db(magnitude([rc], 6000, 44100));
    const at12k = db(magnitude([rc], 12000, 44100));
    expect(at6k - at12k).toBeGreaterThan(5.5);
    expect(at6k - at12k).toBeLessThan(7.5);
  });
});

// ---------------------------------------------------------------------------
// Pure-TS IIR recursion harness (no Web Audio in the test env, review M4).
// ---------------------------------------------------------------------------

function round5(v: number): number {
  return Math.round(v * 100000) / 100000;
}

function db(v: number): number {
  return 20 * Math.log10(v);
}

interface Stage {
  /** Feedforward coefficients, b0..b2 (missing tail = 0). */
  b: number[];
  /** Feedback coefficients, [1, a1, a2] (missing tail = 0). */
  a: number[];
}

function runCascade(stages: Stage[], n = 16384): number[] {
  // Impulse in, impulse response out (zero-padded to n samples).
  let signal = new Array<number>(n).fill(0);
  signal[0] = 1;
  for (const stage of stages) {
    const [b0 = 0, b1 = 0, b2 = 0] = stage.b;
    const [, a1 = 0, a2 = 0] = stage.a;
    const out = new Array<number>(signal.length);
    let x1 = 0, x2 = 0, y1 = 0, y2 = 0;
    for (let n = 0; n < signal.length; n++) {
      const x0 = signal[n]!;
      const y0 = b0 * x0 + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2;
      x2 = x1; x1 = x0; y2 = y1; y1 = y0;
      out[n] = y0;
    }
    signal = out;
  }
  return signal;
}

/**
 * |H(e^{jw})| via a truncated impulse response and a Goertzel-style complex
 * sum: H(e^{jw}) = sum h[n] e^{-jwn}. Both stages' IRs decay below 1e-12
 * within N samples, so truncation error is negligible.
 */
function magnitude(stages: Stage[], freq: number, fs: number): number {
  const h = runCascade(stages);
  const w = (2 * Math.PI * freq) / fs;
  let re = 0;
  let im = 0;
  for (let i = 0; i < h.length; i++) {
    re += h[i]! * Math.cos(w * i);
    im -= h[i]! * Math.sin(w * i);
  }
  return Math.hypot(re, im);
}

function dcGain(stages: Stage[]): number {
  return runCascade(stages).reduce((sum, v) => sum + v, 0);
}